version="0.3.2"

[scripts]
# Releases the project (maintainers only)
# We commit all staged files so we can manually bump the Cargo version
release.cmd = [
    "standard-version --sign --commit-all %%",
    "git push --follow-tags origin main"
]
release.desc = "creates a new project release and pushes it to github (cargo version must be manually bumped)"

# Publishes each package
publish.cmd = "cargo publish %%"
publish.desc = "publishes to crates.io"
